Repository sosbrumadinho/brumadinho_location, pull requests merged in 2019-02, with the labels that each got.

#88 add functions, icons
  frontend/.babelrc
  frontend/.editorconfig
  frontend/.eslintignore
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.postcssrc.js
  frontend/.stylintrc
  frontend/README.md
  frontend/package.json
  frontend/quasar.conf.js
  frontend/src/App.vue
  frontend/src/assets/quasar-logo-full.svg
  frontend/src/assets/sad.svg
  frontend/src/components/.gitkeep
  frontend/src/css/app.styl
  frontend/src/css/themes/common.variables.styl
  frontend/src/css/themes/variables.ios.styl
  frontend/src/css/themes/variables.mat.styl
  frontend/src/index.template.html
  frontend/src/layouts/MyLayout.vue
  frontend/src/pages/Error404.vue
  frontend/src/pages/Index.vue
  frontend/src/plugins/.gitkeep
  frontend/src/plugins/axios.js
  frontend/src/router/index.js
  frontend/src/router/routes.js
  frontend/src/statics/icons/animal.png
  frontend/src/statics/icons/apple-icon-152x152.png
  frontend/src/statics/icons/busca.png
  frontend/src/statics/icons/favicon-16x16.png
  frontend/src/statics/icons/favicon-32x32.png
  frontend/src/statics/icons/icon-128x128.png
  frontend/src/statics/icons/icon-192x192.png
  frontend/src/statics/icons/icon-256x256.png
  frontend/src/statics/icons/icon-384x384.png
  frontend/src/statics/icons/icon-512x512.png
  frontend/src/statics/icons/ms-icon-144x144.png
  frontend/src/statics/icons/person.png
  frontend/src/statics/icons/worker.png
  frontend/src/statics/quasar-logo.png
  frontend/yarn.lock
Labels: awaiting review, in progress

#92 Brumadinho Heatmap Location
  .DS_Store
  brumadinho_heatmap/.gitignore
  brumadinho_heatmap/LICENSE
  brumadinho_heatmap/README.md
  brumadinho_heatmap/misc/coords.geojson
  brumadinho_heatmap/misc/geojson.py
  brumadinho_heatmap/misc/input.json
  brumadinho_heatmap/public/404.html
  brumadinho_heatmap/public/index.html
  brumadinho_heatmap/public/js/.DS_Store
  brumadinho_heatmap/public/js/map.js
  brumadinho_heatmap/public/src/favicon_package_v0.16/.DS_Store
  brumadinho_heatmap/public/src/favicon_package_v0.16/android-chrome-192x192.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/android-chrome-512x512.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/apple-touch-icon.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/browserconfig.xml
  brumadinho_heatmap/public/src/favicon_package_v0.16/favicon-16x16.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/favicon-32x32.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/favicon.ico
  brumadinho_heatmap/public/src/favicon_package_v0.16/mstile-144x144.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/mstile-150x150.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/mstile-310x150.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/mstile-310x310.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/mstile-70x70.png
  brumadinho_heatmap/public/src/favicon_package_v0.16/safari-pinned-tab.svg
  brumadinho_heatmap/public/src/favicon_package_v0.16/site.webmanifest
  brumadinho_heatmap/public/src/imgs/.DS_Store
  brumadinho_heatmap/public/src/imgs/placeholder.svg
Labels: awaiting review

#98 Adding more items to gitignore
  .gitignore
Labels: READY-TO-MERGE
